# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resolved_service_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import steammessages_base_pb2 as steammessages__base__pb2
import steammessages_unified_base_pb2 as steammessages__unified__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='resolved_service_messages.proto',
  package='',
  syntax='proto2',
  serialized_options=b'H\001\220\001\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fresolved_service_messages.proto\x1a\x18steammessages_base.proto\x1a steammessages_unified_base.proto\"T\n1CCommunity_GetAppRichPresenceLocalization_Request\x12\r\n\x05\x61ppid\x18\x01 \x01(\x05\x12\x10\n\x08language\x18\x02 \x01(\t\"\x97\x01\n2CCommunity_GetAppRichPresenceLocalization_Response\x12\r\n\x05\x61ppid\x18\x01 \x01(\x05\x12R\n\x0btoken_lists\x18\x02 \x03(\x0b\x32=.CCommunity_GetAppRichPresenceLocalization_Response_TokenList\"W\n8CCommunity_GetAppRichPresenceLocalization_Response_Token\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x9b\x01\n<CCommunity_GetAppRichPresenceLocalization_Response_TokenList\x12\x10\n\x08language\x18\x01 \x01(\t\x12I\n\x06tokens\x18\x02 \x03(\x0b\x32\x39.CCommunity_GetAppRichPresenceLocalization_Response_Token\"[\n\"CCloudConfigStore_Download_Request\x12\x35\n\x08versions\x18\x01 \x03(\x0b\x32#.CCloudConfigStore_NamespaceVersion\"U\n#CCloudConfigStore_Download_Response\x12.\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32 .CCloudConfigStore_NamespaceData\"m\n\x17\x43\x43loudConfigStore_Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nis_deleted\x18\x02 \x01(\x08\x12\r\n\x05value\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x07\x12\x0f\n\x07version\x18\x05 \x01(\x04\"\x82\x01\n\x1f\x43\x43loudConfigStore_NamespaceData\x12\x12\n\nenamespace\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12)\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x18.CCloudConfigStore_Entry\x12\x0f\n\x07horizon\x18\x04 \x01(\x04\"I\n\"CCloudConfigStore_NamespaceVersion\x12\x12\n\nenamespace\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\x04\x42\x05H\x01\x90\x01\x00'
  ,
  dependencies=[steammessages__base__pb2.DESCRIPTOR,steammessages__unified__base__pb2.DESCRIPTOR,])




_CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_REQUEST = _descriptor.Descriptor(
  name='CCommunity_GetAppRichPresenceLocalization_Request',
  full_name='CCommunity_GetAppRichPresenceLocalization_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='CCommunity_GetAppRichPresenceLocalization_Request.appid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='CCommunity_GetAppRichPresenceLocalization_Request.language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=179,
)


_CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE = _descriptor.Descriptor(
  name='CCommunity_GetAppRichPresenceLocalization_Response',
  full_name='CCommunity_GetAppRichPresenceLocalization_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='CCommunity_GetAppRichPresenceLocalization_Response.appid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token_lists', full_name='CCommunity_GetAppRichPresenceLocalization_Response.token_lists', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=333,
)


_CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKEN = _descriptor.Descriptor(
  name='CCommunity_GetAppRichPresenceLocalization_Response_Token',
  full_name='CCommunity_GetAppRichPresenceLocalization_Response_Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CCommunity_GetAppRichPresenceLocalization_Response_Token.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CCommunity_GetAppRichPresenceLocalization_Response_Token.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=422,
)


_CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKENLIST = _descriptor.Descriptor(
  name='CCommunity_GetAppRichPresenceLocalization_Response_TokenList',
  full_name='CCommunity_GetAppRichPresenceLocalization_Response_TokenList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='CCommunity_GetAppRichPresenceLocalization_Response_TokenList.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='CCommunity_GetAppRichPresenceLocalization_Response_TokenList.tokens', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=580,
)


_CCLOUDCONFIGSTORE_DOWNLOAD_REQUEST = _descriptor.Descriptor(
  name='CCloudConfigStore_Download_Request',
  full_name='CCloudConfigStore_Download_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='versions', full_name='CCloudConfigStore_Download_Request.versions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=582,
  serialized_end=673,
)


_CCLOUDCONFIGSTORE_DOWNLOAD_RESPONSE = _descriptor.Descriptor(
  name='CCloudConfigStore_Download_Response',
  full_name='CCloudConfigStore_Download_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='CCloudConfigStore_Download_Response.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=760,
)


_CCLOUDCONFIGSTORE_ENTRY = _descriptor.Descriptor(
  name='CCloudConfigStore_Entry',
  full_name='CCloudConfigStore_Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CCloudConfigStore_Entry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_deleted', full_name='CCloudConfigStore_Entry.is_deleted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CCloudConfigStore_Entry.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CCloudConfigStore_Entry.timestamp', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='CCloudConfigStore_Entry.version', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=871,
)


_CCLOUDCONFIGSTORE_NAMESPACEDATA = _descriptor.Descriptor(
  name='CCloudConfigStore_NamespaceData',
  full_name='CCloudConfigStore_NamespaceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enamespace', full_name='CCloudConfigStore_NamespaceData.enamespace', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='CCloudConfigStore_NamespaceData.version', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entries', full_name='CCloudConfigStore_NamespaceData.entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='horizon', full_name='CCloudConfigStore_NamespaceData.horizon', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=874,
  serialized_end=1004,
)


_CCLOUDCONFIGSTORE_NAMESPACEVERSION = _descriptor.Descriptor(
  name='CCloudConfigStore_NamespaceVersion',
  full_name='CCloudConfigStore_NamespaceVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enamespace', full_name='CCloudConfigStore_NamespaceVersion.enamespace', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='CCloudConfigStore_NamespaceVersion.version', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1006,
  serialized_end=1079,
)

_CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE.fields_by_name['token_lists'].message_type = _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKENLIST
_CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKENLIST.fields_by_name['tokens'].message_type = _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKEN
_CCLOUDCONFIGSTORE_DOWNLOAD_REQUEST.fields_by_name['versions'].message_type = _CCLOUDCONFIGSTORE_NAMESPACEVERSION
_CCLOUDCONFIGSTORE_DOWNLOAD_RESPONSE.fields_by_name['data'].message_type = _CCLOUDCONFIGSTORE_NAMESPACEDATA
_CCLOUDCONFIGSTORE_NAMESPACEDATA.fields_by_name['entries'].message_type = _CCLOUDCONFIGSTORE_ENTRY
DESCRIPTOR.message_types_by_name['CCommunity_GetAppRichPresenceLocalization_Request'] = _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_REQUEST
DESCRIPTOR.message_types_by_name['CCommunity_GetAppRichPresenceLocalization_Response'] = _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE
DESCRIPTOR.message_types_by_name['CCommunity_GetAppRichPresenceLocalization_Response_Token'] = _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKEN
DESCRIPTOR.message_types_by_name['CCommunity_GetAppRichPresenceLocalization_Response_TokenList'] = _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKENLIST
DESCRIPTOR.message_types_by_name['CCloudConfigStore_Download_Request'] = _CCLOUDCONFIGSTORE_DOWNLOAD_REQUEST
DESCRIPTOR.message_types_by_name['CCloudConfigStore_Download_Response'] = _CCLOUDCONFIGSTORE_DOWNLOAD_RESPONSE
DESCRIPTOR.message_types_by_name['CCloudConfigStore_Entry'] = _CCLOUDCONFIGSTORE_ENTRY
DESCRIPTOR.message_types_by_name['CCloudConfigStore_NamespaceData'] = _CCLOUDCONFIGSTORE_NAMESPACEDATA
DESCRIPTOR.message_types_by_name['CCloudConfigStore_NamespaceVersion'] = _CCLOUDCONFIGSTORE_NAMESPACEVERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CCommunity_GetAppRichPresenceLocalization_Request = _reflection.GeneratedProtocolMessageType('CCommunity_GetAppRichPresenceLocalization_Request', (_message.Message,), {
  'DESCRIPTOR' : _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_REQUEST,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCommunity_GetAppRichPresenceLocalization_Request)
  })
_sym_db.RegisterMessage(CCommunity_GetAppRichPresenceLocalization_Request)

CCommunity_GetAppRichPresenceLocalization_Response = _reflection.GeneratedProtocolMessageType('CCommunity_GetAppRichPresenceLocalization_Response', (_message.Message,), {
  'DESCRIPTOR' : _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCommunity_GetAppRichPresenceLocalization_Response)
  })
_sym_db.RegisterMessage(CCommunity_GetAppRichPresenceLocalization_Response)

CCommunity_GetAppRichPresenceLocalization_Response_Token = _reflection.GeneratedProtocolMessageType('CCommunity_GetAppRichPresenceLocalization_Response_Token', (_message.Message,), {
  'DESCRIPTOR' : _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKEN,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCommunity_GetAppRichPresenceLocalization_Response_Token)
  })
_sym_db.RegisterMessage(CCommunity_GetAppRichPresenceLocalization_Response_Token)

CCommunity_GetAppRichPresenceLocalization_Response_TokenList = _reflection.GeneratedProtocolMessageType('CCommunity_GetAppRichPresenceLocalization_Response_TokenList', (_message.Message,), {
  'DESCRIPTOR' : _CCOMMUNITY_GETAPPRICHPRESENCELOCALIZATION_RESPONSE_TOKENLIST,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCommunity_GetAppRichPresenceLocalization_Response_TokenList)
  })
_sym_db.RegisterMessage(CCommunity_GetAppRichPresenceLocalization_Response_TokenList)

CCloudConfigStore_Download_Request = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Download_Request', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_DOWNLOAD_REQUEST,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Download_Request)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Download_Request)

CCloudConfigStore_Download_Response = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Download_Response', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_DOWNLOAD_RESPONSE,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Download_Response)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Download_Response)

CCloudConfigStore_Entry = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Entry', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_ENTRY,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Entry)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Entry)

CCloudConfigStore_NamespaceData = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_NamespaceData', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_NAMESPACEDATA,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_NamespaceData)
  })
_sym_db.RegisterMessage(CCloudConfigStore_NamespaceData)

CCloudConfigStore_NamespaceVersion = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_NamespaceVersion', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_NAMESPACEVERSION,
  '__module__' : 'resolved_service_messages_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_NamespaceVersion)
  })
_sym_db.RegisterMessage(CCloudConfigStore_NamespaceVersion)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
