# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: service_cloudconfigstore.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class CCloudConfigStore_Change_Notification(betterproto.Message):
    versions: List["CCloudConfigStore_NamespaceVersion"] = betterproto.message_field(2)


@dataclass
class CCloudConfigStore_Download_Request(betterproto.Message):
    versions: List["CCloudConfigStore_NamespaceVersion"] = betterproto.message_field(1)


@dataclass
class CCloudConfigStore_Download_Response(betterproto.Message):
    data: List["CCloudConfigStore_NamespaceData"] = betterproto.message_field(1)


@dataclass
class CCloudConfigStore_Entry(betterproto.Message):
    key: str = betterproto.string_field(1)
    is_deleted: bool = betterproto.bool_field(2)
    value: str = betterproto.string_field(3)
    timestamp: float = betterproto.fixed32_field(4)
    version: int = betterproto.uint64_field(5)


@dataclass
class CCloudConfigStore_NamespaceData(betterproto.Message):
    enamespace: int = betterproto.uint32_field(1)
    version: int = betterproto.uint64_field(2)
    entries: List["CCloudConfigStore_Entry"] = betterproto.message_field(3)
    horizon: int = betterproto.uint64_field(4)


@dataclass
class CCloudConfigStore_NamespaceVersion(betterproto.Message):
    enamespace: int = betterproto.uint32_field(1)
    version: int = betterproto.uint64_field(2)


@dataclass
class CCloudConfigStore_Upload_Request(betterproto.Message):
    data: List["CCloudConfigStore_NamespaceData"] = betterproto.message_field(1)


@dataclass
class CCloudConfigStore_Upload_Response(betterproto.Message):
    versions: List["CCloudConfigStore_NamespaceVersion"] = betterproto.message_field(1)
