# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_cloudconfigstore.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import steammessages_unified_base_pb2 as steammessages__unified__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eservice_cloudconfigstore.proto\x1a steammessages_unified_base.proto\"^\n%CCloudConfigStore_Change_Notification\x12\x35\n\x08versions\x18\x02 \x03(\x0b\x32#.CCloudConfigStore_NamespaceVersion\"[\n\"CCloudConfigStore_Download_Request\x12\x35\n\x08versions\x18\x01 \x03(\x0b\x32#.CCloudConfigStore_NamespaceVersion\"U\n#CCloudConfigStore_Download_Response\x12.\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32 .CCloudConfigStore_NamespaceData\"m\n\x17\x43\x43loudConfigStore_Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nis_deleted\x18\x02 \x01(\x08\x12\r\n\x05value\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x07\x12\x0f\n\x07version\x18\x05 \x01(\x04\"\x82\x01\n\x1f\x43\x43loudConfigStore_NamespaceData\x12\x12\n\nenamespace\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12)\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x18.CCloudConfigStore_Entry\x12\x0f\n\x07horizon\x18\x04 \x01(\x04\"I\n\"CCloudConfigStore_NamespaceVersion\x12\x12\n\nenamespace\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\x04\"R\n CCloudConfigStore_Upload_Request\x12.\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32 .CCloudConfigStore_NamespaceData\"Z\n!CCloudConfigStore_Upload_Response\x12\x35\n\x08versions\x18\x01 \x03(\x0b\x32#.CCloudConfigStore_NamespaceVersion2\xba\x01\n\x10\x43loudConfigStore\x12U\n\x08\x44ownload\x12#.CCloudConfigStore_Download_Request\x1a$.CCloudConfigStore_Download_Response\x12O\n\x06Upload\x12!.CCloudConfigStore_Upload_Request\x1a\".CCloudConfigStore_Upload_Response2]\n\x16\x43loudConfigStoreClient\x12\x43\n\x0cNotifyChange\x12&.CCloudConfigStore_Change_Notification\x1a\x0b.NoResponse')



_CCLOUDCONFIGSTORE_CHANGE_NOTIFICATION = DESCRIPTOR.message_types_by_name['CCloudConfigStore_Change_Notification']
_CCLOUDCONFIGSTORE_DOWNLOAD_REQUEST = DESCRIPTOR.message_types_by_name['CCloudConfigStore_Download_Request']
_CCLOUDCONFIGSTORE_DOWNLOAD_RESPONSE = DESCRIPTOR.message_types_by_name['CCloudConfigStore_Download_Response']
_CCLOUDCONFIGSTORE_ENTRY = DESCRIPTOR.message_types_by_name['CCloudConfigStore_Entry']
_CCLOUDCONFIGSTORE_NAMESPACEDATA = DESCRIPTOR.message_types_by_name['CCloudConfigStore_NamespaceData']
_CCLOUDCONFIGSTORE_NAMESPACEVERSION = DESCRIPTOR.message_types_by_name['CCloudConfigStore_NamespaceVersion']
_CCLOUDCONFIGSTORE_UPLOAD_REQUEST = DESCRIPTOR.message_types_by_name['CCloudConfigStore_Upload_Request']
_CCLOUDCONFIGSTORE_UPLOAD_RESPONSE = DESCRIPTOR.message_types_by_name['CCloudConfigStore_Upload_Response']
CCloudConfigStore_Change_Notification = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Change_Notification', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_CHANGE_NOTIFICATION,
  '__module__' : 'service_cloudconfigstore_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Change_Notification)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Change_Notification)

CCloudConfigStore_Download_Request = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Download_Request', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_DOWNLOAD_REQUEST,
  '__module__' : 'service_cloudconfigstore_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Download_Request)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Download_Request)

CCloudConfigStore_Download_Response = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Download_Response', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_DOWNLOAD_RESPONSE,
  '__module__' : 'service_cloudconfigstore_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Download_Response)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Download_Response)

CCloudConfigStore_Entry = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Entry', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_ENTRY,
  '__module__' : 'service_cloudconfigstore_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Entry)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Entry)

CCloudConfigStore_NamespaceData = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_NamespaceData', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_NAMESPACEDATA,
  '__module__' : 'service_cloudconfigstore_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_NamespaceData)
  })
_sym_db.RegisterMessage(CCloudConfigStore_NamespaceData)

CCloudConfigStore_NamespaceVersion = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_NamespaceVersion', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_NAMESPACEVERSION,
  '__module__' : 'service_cloudconfigstore_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_NamespaceVersion)
  })
_sym_db.RegisterMessage(CCloudConfigStore_NamespaceVersion)

CCloudConfigStore_Upload_Request = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Upload_Request', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_UPLOAD_REQUEST,
  '__module__' : 'service_cloudconfigstore_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Upload_Request)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Upload_Request)

CCloudConfigStore_Upload_Response = _reflection.GeneratedProtocolMessageType('CCloudConfigStore_Upload_Response', (_message.Message,), {
  'DESCRIPTOR' : _CCLOUDCONFIGSTORE_UPLOAD_RESPONSE,
  '__module__' : 'service_cloudconfigstore_pb2'
  # @@protoc_insertion_point(class_scope:CCloudConfigStore_Upload_Response)
  })
_sym_db.RegisterMessage(CCloudConfigStore_Upload_Response)

_CLOUDCONFIGSTORE = DESCRIPTOR.services_by_name['CloudConfigStore']
_CLOUDCONFIGSTORECLIENT = DESCRIPTOR.services_by_name['CloudConfigStoreClient']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CCLOUDCONFIGSTORE_CHANGE_NOTIFICATION._serialized_start=68
  _CCLOUDCONFIGSTORE_CHANGE_NOTIFICATION._serialized_end=162
  _CCLOUDCONFIGSTORE_DOWNLOAD_REQUEST._serialized_start=164
  _CCLOUDCONFIGSTORE_DOWNLOAD_REQUEST._serialized_end=255
  _CCLOUDCONFIGSTORE_DOWNLOAD_RESPONSE._serialized_start=257
  _CCLOUDCONFIGSTORE_DOWNLOAD_RESPONSE._serialized_end=342
  _CCLOUDCONFIGSTORE_ENTRY._serialized_start=344
  _CCLOUDCONFIGSTORE_ENTRY._serialized_end=453
  _CCLOUDCONFIGSTORE_NAMESPACEDATA._serialized_start=456
  _CCLOUDCONFIGSTORE_NAMESPACEDATA._serialized_end=586
  _CCLOUDCONFIGSTORE_NAMESPACEVERSION._serialized_start=588
  _CCLOUDCONFIGSTORE_NAMESPACEVERSION._serialized_end=661
  _CCLOUDCONFIGSTORE_UPLOAD_REQUEST._serialized_start=663
  _CCLOUDCONFIGSTORE_UPLOAD_REQUEST._serialized_end=745
  _CCLOUDCONFIGSTORE_UPLOAD_RESPONSE._serialized_start=747
  _CCLOUDCONFIGSTORE_UPLOAD_RESPONSE._serialized_end=837
  _CLOUDCONFIGSTORE._serialized_start=840
  _CLOUDCONFIGSTORE._serialized_end=1026
  _CLOUDCONFIGSTORECLIENT._serialized_start=1028
  _CLOUDCONFIGSTORECLIENT._serialized_end=1121
# @@protoc_insertion_point(module_scope)
