# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steammessages_player.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import steammessages_unified_base_pb2 as steammessages__unified__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steammessages_player.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n\x1asteammessages_player.proto\x1a steammessages_unified_base.proto\"\x88\x01\n(CPlayer_CustomGetLastPlayedTimes_Request\x12\\\n\x0fmin_last_played\x18\x01 \x01(\rBC\x82\xb5\x18?The most recent last-played time the client already knows about\"\xe4\x01\n)CPlayer_CustomGetLastPlayedTimes_Response\x12>\n\x05games\x18\x01 \x03(\x0b\x32/.CPlayer_CustomGetLastPlayedTimes_Response.Game\x1aw\n\x04Game\x12\r\n\x05\x61ppid\x18\x01 \x01(\x05\x12\x15\n\rlast_playtime\x18\x02 \x01(\r\x12\x17\n\x0fplaytime_2weeks\x18\x03 \x01(\x05\x12\x18\n\x10playtime_forever\x18\x04 \x01(\x05\x12\x16\n\x0e\x66irst_playtime\x18\x05 \x01(\r2\xe1\x01\n\x0c\x43ustomPlayer\x12\xa1\x01\n\x18\x43lientGetLastPlayedTimes\x12).CPlayer_CustomGetLastPlayedTimes_Request\x1a*.CPlayer_CustomGetLastPlayedTimes_Response\".\x82\xb5\x18*Gets the last-played times for the account\x1a-\x82\xb5\x18)A service for accessing Steam player data2D\n\x12\x43ustomPlayerClient\x1a.\x82\xb5\x18&Steam player data client notifications\xc0\xb5\x18\x02\x42\x03\x90\x01\x01')
  ,
  dependencies=[steammessages__unified__base__pb2.DESCRIPTOR,])




_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_REQUEST = _descriptor.Descriptor(
  name='CPlayer_CustomGetLastPlayedTimes_Request',
  full_name='CPlayer_CustomGetLastPlayedTimes_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_last_played', full_name='CPlayer_CustomGetLastPlayedTimes_Request.min_last_played', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030?The most recent last-played time the client already knows about'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=201,
)


_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='CPlayer_CustomGetLastPlayedTimes_Response.Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='CPlayer_CustomGetLastPlayedTimes_Response.Game.appid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_playtime', full_name='CPlayer_CustomGetLastPlayedTimes_Response.Game.last_playtime', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playtime_2weeks', full_name='CPlayer_CustomGetLastPlayedTimes_Response.Game.playtime_2weeks', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playtime_forever', full_name='CPlayer_CustomGetLastPlayedTimes_Response.Game.playtime_forever', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_playtime', full_name='CPlayer_CustomGetLastPlayedTimes_Response.Game.first_playtime', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=432,
)

_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE = _descriptor.Descriptor(
  name='CPlayer_CustomGetLastPlayedTimes_Response',
  full_name='CPlayer_CustomGetLastPlayedTimes_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='games', full_name='CPlayer_CustomGetLastPlayedTimes_Response.games', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE_GAME, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=432,
)

_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE_GAME.containing_type = _CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE
_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE.fields_by_name['games'].message_type = _CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE_GAME
DESCRIPTOR.message_types_by_name['CPlayer_CustomGetLastPlayedTimes_Request'] = _CPLAYER_CUSTOMGETLASTPLAYEDTIMES_REQUEST
DESCRIPTOR.message_types_by_name['CPlayer_CustomGetLastPlayedTimes_Response'] = _CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CPlayer_CustomGetLastPlayedTimes_Request = _reflection.GeneratedProtocolMessageType('CPlayer_CustomGetLastPlayedTimes_Request', (_message.Message,), {
  'DESCRIPTOR' : _CPLAYER_CUSTOMGETLASTPLAYEDTIMES_REQUEST,
  '__module__' : 'steammessages_player_pb2'
  # @@protoc_insertion_point(class_scope:CPlayer_CustomGetLastPlayedTimes_Request)
  })
_sym_db.RegisterMessage(CPlayer_CustomGetLastPlayedTimes_Request)

CPlayer_CustomGetLastPlayedTimes_Response = _reflection.GeneratedProtocolMessageType('CPlayer_CustomGetLastPlayedTimes_Response', (_message.Message,), {

  'Game' : _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
    'DESCRIPTOR' : _CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE_GAME,
    '__module__' : 'steammessages_player_pb2'
    # @@protoc_insertion_point(class_scope:CPlayer_CustomGetLastPlayedTimes_Response.Game)
    })
  ,
  'DESCRIPTOR' : _CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE,
  '__module__' : 'steammessages_player_pb2'
  # @@protoc_insertion_point(class_scope:CPlayer_CustomGetLastPlayedTimes_Response)
  })
_sym_db.RegisterMessage(CPlayer_CustomGetLastPlayedTimes_Response)
_sym_db.RegisterMessage(CPlayer_CustomGetLastPlayedTimes_Response.Game)


DESCRIPTOR._options = None
_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_REQUEST.fields_by_name['min_last_played']._options = None

_CUSTOMPLAYER = _descriptor.ServiceDescriptor(
  name='CustomPlayer',
  full_name='CustomPlayer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\202\265\030)A service for accessing Steam player data'),
  serialized_start=435,
  serialized_end=660,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClientGetLastPlayedTimes',
    full_name='CustomPlayer.ClientGetLastPlayedTimes',
    index=0,
    containing_service=None,
    input_type=_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_REQUEST,
    output_type=_CPLAYER_CUSTOMGETLASTPLAYEDTIMES_RESPONSE,
    serialized_options=_b('\202\265\030*Gets the last-played times for the account'),
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMPLAYER)

DESCRIPTOR.services_by_name['CustomPlayer'] = _CUSTOMPLAYER


_CUSTOMPLAYERCLIENT = _descriptor.ServiceDescriptor(
  name='CustomPlayerClient',
  full_name='CustomPlayerClient',
  file=DESCRIPTOR,
  index=1,
  serialized_options=_b('\202\265\030&Steam player data client notifications\300\265\030\002'),
  serialized_start=662,
  serialized_end=730,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_CUSTOMPLAYERCLIENT)

DESCRIPTOR.services_by_name['CustomPlayerClient'] = _CUSTOMPLAYERCLIENT

CustomPlayer = service_reflection.GeneratedServiceType('CustomPlayer', (_service.Service,), dict(
  DESCRIPTOR = _CUSTOMPLAYER,
  __module__ = 'steammessages_player_pb2'
  ))

CustomPlayer_Stub = service_reflection.GeneratedServiceStubType('CustomPlayer_Stub', (CustomPlayer,), dict(
  DESCRIPTOR = _CUSTOMPLAYER,
  __module__ = 'steammessages_player_pb2'
  ))


CustomPlayerClient = service_reflection.GeneratedServiceType('CustomPlayerClient', (_service.Service,), dict(
  DESCRIPTOR = _CUSTOMPLAYERCLIENT,
  __module__ = 'steammessages_player_pb2'
  ))

CustomPlayerClient_Stub = service_reflection.GeneratedServiceStubType('CustomPlayerClient_Stub', (CustomPlayerClient,), dict(
  DESCRIPTOR = _CUSTOMPLAYERCLIENT,
  __module__ = 'steammessages_player_pb2'
  ))


# @@protoc_insertion_point(module_scope)
